/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.tgiachi.stars.network;

import com.github.tgiachi.stars.network.builders.NetworkMessageBuilder;
import com.github.tgiachi.stars.network.messages.PingMessageRequest;
import org.junit.Assert;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

class MessagesTest {
    @Test
    void compressMessage() throws Exception {
       var pingMessage = PingMessageRequest
               .builder().ping(true).build();
        var udpMessage = NetworkMessageBuilder.buildMessage(pingMessage);

        Assert.assertNotNull(udpMessage);
    }
}
